# includes/excludes all rules by default
default: true

# 4-space list indentation works best with MkDocs
MD007:
  indent: 4

# Remove line length limit - no one wants to hard wrap all their paragraphs
MD013: false

# Remove code indent format error because it incorrectly catches admonitions
MD046: false

# allow duplicate sub-headings
MD024: false

# allow inline HTML
MD033: false

# throwing a false positive on the email link
MD034: false

# in some cases, emphasis really is more appropriate than a heading
MD036: false
