site_name: "Transit Operational Data Standard"
site_url: https://ods.calitp.org
repo_url: https://github.com/cal-itp/operational-data-standard
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate
  palette:
    primary: "blue"
    accent: "amber"
  icon:
    logo: material/bus

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
