name: Lint and style checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit/action@v3.0.1